### ISSUE TITLE
deprecate in favour of 'language-asn' and 'snmp'

### ISSUE THREAD

**Issue by chessai** [andrewthad/asn1-codec#9]
language-asn is now on hackage: http://hackage.haskell.org/package/language-asn
snmp is now on hackage: http://hackage.haskell.org/package/snmp

we should deprecate asn1-codec in favour of these two libraries. furthermore, it may be advantageous from a maintainer's perspective to hold the source of both of these libraries under a monorepo. I can transfer ownership of them to you if you prefer, or one of us can just create a new repo and shove both projects in it.

**Comment by andrewthad** [comment]
Yeah, let's deprecate `asn1-codec`. The monorepo would be more useful if `language-asn` had a less stable interface, but I think it's actually pretty stable at this point. Can you make a github organization and put the two repositories there and then make us both admins? I think that should work well, and it makes the coupling somewhat explicit.
